export { DisposableStore, type Disposable } from './Disposable';
export {
  createGitHubReleaseBundleUpdateResolver,
  type GitHubReleaseBundleUpdateOptions,
} from './BundleUpdates';
export {
  createExternalLoginFlow,
  type SiteExternalLoginFlow,
  type SiteExternalLoginFlowOptions,
} from './ExternalLoginFlow';
export {
  getPluginMetadata,
  getProviderMetadata,
  plugin,
  provider,
} from './Decorators';
export {
  defineProviderLocale,
  type ProviderLocale,
  type ProviderLocaleResource,
} from './Locale';
export {
  AbstractPlugin,
  KAWAIKARA_MANIFEST_VERSION,
  KAWAIKARA_SITE_API_VERSION,
  defineBundle,
  definePlugin,
  defineProvider,
  isBundleDefinition,
  type BundleBrowserProfileContribution,
  type BundleDefinition,
  type BundleManifest,
  type BundleLocaleContribution,
  type BundleReleaseChannel,
  type BundleUpdateContext,
  type BundleUpdateDefinition,
  type BundleUpdateManifest,
  type BundleUpdateResolver,
  type PluginConstructor,
  type PluginContext,
  type PluginMetadata,
  type PluginDefinition,
  type PluginManifest,
  type ProviderDefinition,
  type ProviderManifest,
  type ProviderManifestContributions,
} from './Plugin';
export {
  AbstractProvider,
  AbstractUrlProvider,
  type ProviderConstructor,
  type ProviderDecoratorMetadata,
  type ProviderBooleanSettingContribution,
  type ProviderItemListSettingContribution,
  type ProviderLocalizedText,
  type PluginViewPanelContent,
  type PluginViewPanelContribution,
  type ProviderMetadata,
  type ProviderSettingCategoryContribution,
  type ProviderSettingContribution,
  type ProviderSettingListItem,
  type ProviderSettingValue,
  type ProviderSettingsContribution,
  type ProviderSettings,
  type SiteActionShortcutContribution,
  type SiteAddressContribution,
  type SiteMenuContribution,
  type SiteLocaleContribution,
  type SiteIsolationContribution,
  type SitePermission,
  type SitePictureInPictureContribution,
  type SiteRequestDetails,
  type SiteRequestHeaders,
  type SiteRequestRedirect,
  type SiteShortcutContribution,
} from './Provider';
export {
  SHORT_FORM_VIDEO_ACTIONS,
  SHORT_FORM_VIDEO_AUTO_ADVANCE_SETTING,
  SHORT_FORM_VIDEO_BANNED_PUBLISHERS_SETTING,
  normalizeShortFormVideoPublisher,
  readShortFormVideoAutoAdvance,
  readShortFormVideoBannedPublishers,
  resolveShortFormVideoCommand,
  type ShortFormVideoContribution,
  type ShortFormVideoAction,
  type ShortFormVideoCommand,
  type ShortFormVideoPublisher,
} from './ShortFormVideo';
export {
  type ExternalLoginOptions,
  type ExternalLoginResult,
  type NewWindowPolicy,
  type SiteActions,
  type SiteBrowser,
  type SiteBrowserIdentityOptions,
  type SiteCookieClearOptions,
  type SiteCookieMetadata,
  type SiteCookieQuery,
  type SiteCookieStore,
  type SiteContext,
  type SiteExternalBrowser,
  type SiteLogger,
  type SiteLocaleContext,
  type SitePageFrameScope,
  type SitePageInjection,
  type SitePagePhase,
  type SitePagePipeline,
  type SiteViewer,
} from './SiteContext';
export {
  createChromiumClientHints,
  createChromiumUserAgent,
  createLoginControlInjection,
  isSiteLoginNavigation,
  matchesSiteUrlHost,
  resolveLocaleVariant,
  serializePageInjection,
  serializePageInjectionWithOptions,
  setRequestHeader,
  webAuthenticationPolicy,
  webPopupPolicy,
  type SiteLoginControlInjectionOptions,
} from './SiteUtilities';
